@host=0.0.0.0:8000
@username=admin
@password=admin123

###

# @name init
POST http://{{host}}/api/app-init?admin=Admin


###

# @name login
GET http://{{host}}/api/login?username={{username}}&passwd={{password}}

@accessToken={{login.response.body.$.accessToken}}
@refreshToken={{login.response.body.$.refreshToken}}

###
# @name refresh
GET http://{{host}}/api/refresh
Authorization: Bearer {{login.response.body.$.refreshToken}}

#@accessToken={{refresh.response.body.$.accessToken}}

###
DELETE http://{{host}}/api/revoke
Authorization: Bearer {{refreshToken}}

###
GET http://{{host}}/api/_admin/routes
Authorization: Bearer {{accessToken}}

###
GET http://{{host}}/api/_admin/endpoint/stats
Authorization: Bearer {{accessToken}}

###
GET http://{{host}}/api/_admin/endpoint/stats
Authorization: Bearer {{accessToken}}
