name: Development Build

on:
  pull_request:
    - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container: suilteam/base:ubuntu

    steps:
      - uses: actions/checkout@v2
      # Create a build directory
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      # Configure CMake project
      - name: Configure CMake
        shell: bash
        run: |
          cd ${{runner.workspace}}/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      # Build project
      - name: Build Dependecies
        shell: bash
        run: |
          cd ${{runner.workspace}}/build
          make deps -j4

      # Build project
      - name: Build
        shell: bash
        run: |
          cd ${{runner.workspace}}/build
          make -j4

      - name: Cached Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-binaries
          path: ${{runner.workspace}}/build/**/*_unittest
          retention-days: 1
