name: Development Build

on:
  push:
    tags:
      - v*
env:
  VERSION: 0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    container: suilteam/base:alpine
    strategy:
      matrix:
        type: [Debug, Release]

    steps:
      - uses: actions/checkout@v2
      # Create a build directory
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.type }}

      # Configure CMake project
      - name: Configure CMake
        shell: bash
        run: |
          cd ${{runner.workspace}}/build-${{ matrix.type }}
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/artifacts/${{ matrix.type }} -DSUIL_VERSION=$VERSION

      # Build project dependencies
      - name: Build Dependecies
        shell: bash
        run: |
          cd ${{runner.workspace}}/build-${{ matrix.type }}
          make catch -j4

      # Build project
      - name: Build
        shell: bash
        run: |
          cd ${{runner.workspace}}/build-${{ matrix.type }}
          make -j4 install

      - name: UnitTests
        shell: bash
        run: |
          cd ${{runner.workspace}}/build-${{ matrix.type }}
          ./libs/base/base_unittest -r junit -o base_unittest.xml
          ./libs/network/net_unittest -r junit -o net_unittest.xml
          ./libs/database/db_unittest -r junit -o db_unittest.xml
          ./libs/rpc/rpc_unittest -r junit -o rpc_unittest.xml
          ./libs/http/httpserver_unittest -r junit -o httpserver_unittest.xml
          ./libs/http/httpclient_unittest -r junit -o httpclient_unittest.xml

      - name: Create Release Artifact
        shell: bash
        run: |
          cd ${{runner.workspace}}/build-${{ matrix.type }}
          make package

      - name: Create Release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Initial release
          draft: false
          prerelease: false

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          assert_path: ${{runner.workspace}}/build-${{ matrix.type }}/Suil-$VERSION-${{ matrix.type }}.tar.gz
          assert_name: Suil-$VERSION-${{ matrix.type }}.tar.gz
          asset_content_type: application/zip
